// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyrzncmtnctsjnuvholy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cnpuY210bmN0c2pudXZob2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDE3NjksImV4cCI6MjA2NTU3Nzc2OX0.VjXtaWVl6OCATwZUbXFGb26wa1BQAW-SRizrBfeauYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);